import { Post } from './post';
import { Project } from './project';
export class Employee{
  id!: number;
  firstName! : String;
  lastName! : String;
  cin! : number;
  deleveryDate! : Date;
  adresse! : String;
  birthDate! : Date;
  childNumber! : number;
  personalPhone! : String;
  professionalPhone! : String;
  personalMail! : String;
  professionalMail! : String;
  password! : String;
  holidayNumber! : number;
  folder! : String;
  statusF!: String;
  //lastDay! : Date;
  archived! : boolean;
  jobId! : number;
  companyId!:number;
  role!:String;
  url!:String;
  office!:String;
  department!:String;
  job!:String;
  posts!:Post[];
  projects!:Project[];
  ActiveProject!:Project[];
}
